import { HeadlessClient, type Handle } from "../../src/headless/client";
import type { NativeDeclarations } from "../../src/headless/declarations";
import { f32 } from "../../src/sim/f32";

export function coreFixture(declarations: NativeDeclarations): number {
  const client = new HeadlessClient({ slot: 0, humans: [0], declarations, filePrefix: "warcraft3", localNatives: {}, network: [], screenWidth: 1920 });
  const tested = new Set<string>();
  const call = (name: string, ...args: unknown[]) => {
    const fn = client.natives[name];
    if (typeof fn !== "function") throw new Error(`missing declaration ${name}`);
    tested.add(name);
    return (fn as (this: void, ...args: unknown[]) => unknown)(...args);
  };
  const equal = (actual: unknown, expected: unknown, name: string) => { if (actual !== expected) throw new Error(`${name}: ${String(actual)} != ${String(expected)}`); };
  const unit = call("CreateUnit", 0, 123, 0, 0, 0) as Handle;
  const second = call("CreateUnit", 0, 124, 0, 0, 0) as Handle;
  call("UnitAddAbility", unit, 456);
  call("BlzSetUnitAbilityCooldown", unit, 456, 0, 8);
  call("BlzSetUnitAbilityCooldownRemaining", unit, 456, 6);
  equal(call("BlzGetUnitAbilityCooldownRemaining", unit, 456), 6, "remaining setter");
  equal(call("BlzGetUnitAbilityCooldownPercent", unit, 456), f32(0.75), "remaining percent");
  call("BlzSetUnitAbilityCooldownPercent", unit, 456, f32(0.5));
  equal(call("BlzGetUnitAbilityCooldownRemaining", unit, 456), 4, "percent setter");
  call("BlzAdjustUnitAbilityCooldownRemaining", unit, 456, -1);
  equal(call("BlzGetUnitAbilityCooldownRemaining", unit, 456), 3, "remaining adjustment");
  call("BlzAdjustUnitAbilityCooldownPercent", unit, 456, f32(0.25));
  equal(call("BlzGetUnitAbilityCooldownRemaining", unit, 456), 5, "percent adjustment");
  equal(call("BlzGetUnitAbilityCooldownRemaining", second, 456), 0, "unit isolation");
  client.abilities.tick(1);
  equal(call("BlzGetUnitAbilityCooldownRemaining", unit, 456), 4, "cooldown clock");
  call("BlzSetUnitAttackCooldown", unit, 2, 0);
  call("BlzSetUnitAttackCooldown", unit, 3, 1);
  client.abilities.state(unit).attackRemaining.set(0, 2);
  client.abilities.state(unit).attackRemaining.set(1, 3);
  call("BlzResetUnitAttack", unit, 1);
  equal(client.abilities.state(unit).attackRemaining.get(0), 2, "other weapon retained");
  equal(client.abilities.state(unit).attackRemaining.get(1), 0, "attack reset");
  equal(call("BlzGetUnitAttackCooldown", unit, 1), 3, "configured attack period retained");
  call("BlzUnitEnableAuras", unit, false, false);
  equal(client.abilities.state(unit).auras, false, "auras off");
  equal(client.abilities.state(unit).auraUI, true, "aura UI retained");
  call("BlzUnitEnableAuras", unit, false, true);
  equal(client.abilities.state(unit).auraUI, false, "aura UI off");
  const ability = call("BlzGetUnitAbility", unit, 456);
  for (const [name, type] of declarations.constants) {
    if (type !== "abilityreallevelfield" || !name.startsWith("ABILITY_RLF_ALLY_") && !name.startsWith("ABILITY_RLF_ENEMY_") && !name.includes("BONUS_CRITICAL_STRIKE")) continue;
    equal(call("BlzSetAbilityRealLevelField", ability, client.natives[name], 0, f32(0.25)), true, name);
    equal(call("BlzGetAbilityRealLevelField", ability, client.natives[name], 0), f32(0.25), name);
  }
  const effect = call("AddSpecialEffect", "fixture.mdx", 0, 0) as Handle;
  call("BlzSetSpecialEffectAnimationBlendTime", effect, f32(0.5));
  equal(client.effectPoses().find(pose => pose.handle === effect)?.animationBlendTime, f32(0.5), "effect blend");
  call("BlzSetSpecialEffectAnimation", effect, "birth");
  call("BlzQueueSpecialEffectAnimation", effect, "stand");
  equal(client.effectPoses().find(pose => pose.handle === effect)?.animation, "birth", "current animation");
  equal(client.effectPoses().find(pose => pose.handle === effect)?.queuedAnimations[0], "stand", "queued animation");
  call("BlzRemoveEffect", effect);
  equal(client.effectPoses().some(pose => pose.handle === effect), false, "removed effect");
  const frame = call("BlzCreateFrameByType", "TEXTAREA", "fixture", undefined, "", 0) as Handle;
  call("BlzTextAreaFrameSetAutoScroll", frame, false);
  equal(client.textAreaAutoScroll.get(frame), false, "text auto scroll");
  client.key(0, 65, 2, true);
  equal(call("BlzIsKeyPressed", 65), true, "key held");
  equal(call("BlzIsMetaKeyPressed", 2), true, "meta held");
  client.key(0, 65, 0, false);
  equal(call("BlzIsKeyPressed", 65), false, "key released");
  client.heldMouseButtons.add("MOUSE_BUTTON_TYPE_LEFT");
  equal(call("BlzIsMouseButtonPressed", "MOUSE_BUTTON_TYPE_LEFT"), true, "mouse held");
  client.mouseScreenX = 960;
  client.mouseScreenY = 540;
  equal(call("BlzGetMouseScreenPosX"), 960, "mouse x");
  equal(call("BlzGetMouseScreenPosY"), 540, "mouse y");
  equal(call("BlzPixelToFrameX", 960), f32(0.4), "pixel x");
  equal(call("BlzPixelToFrameY", 540), f32(0.3), "pixel y");
  equal(call("BlzFrameToPixelX", f32(0.4)), 960, "frame x");
  equal(call("BlzFrameToPixelY", f32(0.3)), 540, "frame y");
  const trigger = call("CreateTrigger");
  equal(call("BlzTriggerIsRunning", trigger), false, "idle trigger");
  let actions = 0;
  call("TriggerRegisterPlayerChatEvent", trigger, 0, "test", true);
  call("TriggerAddAction", trigger, () => {
    equal(call("BlzTriggerIsRunning", trigger), true, "running trigger");
    actions++;
    call("BlzTriggerInterrupt", trigger);
  });
  call("TriggerAddAction", trigger, () => { actions++; });
  client.chat(0, "test");
  equal(actions, 1, "interrupted trigger");
  equal(client.missingNatives.length, 0, "native coverage");
  return tested.size;
}
