export const REPRO_VIEWER_PAGE = `<!doctype html><html><head><meta charset="utf-8"><title>Saved match</title><style>
body{font:16px system-ui;background:#151b25;color:#edf2fa;margin:32px}input{width:100%}table{border-collapse:collapse;width:100%;font:14px monospace}td,th{text-align:left;padding:8px;border-bottom:1px solid #344054;vertical-align:top;white-space:pre-wrap;overflow-wrap:anywhere}a{color:#9bc7ff}.changed{background:#3c351f}.different{outline:1px solid #e69371}details{margin:6px 0 6px 14px}summary{cursor:pointer}#error{color:#ffb4a1}button{padding:8px}pre{white-space:pre-wrap}</style></head><body>
<h1>Saved match</h1><p id="meta"></p><button id="diverge" hidden>First differing frame</button><label>Frame <output id="number"></output><input id="slider" type="range" step="1"></label><p id="error"></p><table><thead><tr><th>State field</th><th>Client 0</th><th>Client 1</th></tr></thead><tbody id="rows"></tbody></table><details><summary>Canonical state text</summary><pre id="canonical"></pre></details>
<script>
const slider=document.querySelector('#slider'),rows=document.querySelector('#rows');let serial=0;
function tree(fields){const root={};for(const field of fields){let node=root;const keys=field.path.replace(/\\[(\\d+)\\]/g,'.$1').split('.');for(const key of keys){node.children??={};node.children[key]??={};node=node.children[key]}node.field=field}return root}
function render(node,parent,prefix,maps,changes,differences){for(const [key,child] of Object.entries(node.children??{})){const path=prefix?prefix+'.'+key:key;if(child.children){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;const details=document.createElement('details');details.open=true;const summary=document.createElement('summary');summary.textContent=key;details.append(summary);const table=document.createElement('table');details.append(table);td.append(details);tr.append(td);parent.append(tr);render(child,table,path,maps,changes,differences)}if(child.field){const f=child.field,tr=document.createElement('tr');if(changes.has(f.path))tr.classList.add('changed');if(differences.has(f.path))tr.classList.add('different');const td=document.createElement('td');td.textContent=key;if(f.source){const a=document.createElement('a');a.href='/source?file='+encodeURIComponent(f.source.file)+'#L'+f.source.line;a.target='_blank';a.textContent=' '+f.source.file+':'+f.source.line;td.append(a)}tr.append(td);for(const map of maps){const cell=document.createElement('td');cell.textContent=map.get(f.path)??'absent';tr.append(cell)}parent.append(tr)}}}
async function show(){const id=++serial;document.querySelector('#number').textContent=slider.value;try{const response=await fetch('/frame?frame='+slider.value),data=await response.json();if(id!==serial)return;if(data.error)throw Error(data.error);rows.replaceChildren();const fields=new Map(data.clients.flatMap(c=>c.fields).map(f=>[f.path,f]));const maps=data.clients.map(c=>new Map(c.fields.map(f=>[f.path,f.value])));render(tree([...fields.values()].sort((a,b)=>a.path.localeCompare(b.path))),rows,'',maps,new Set(data.clients.flatMap(c=>c.changes.map(f=>f.path))),new Set(data.differences.map(f=>f.path)));document.querySelector('#canonical').textContent=data.clients.map(c=>'Client '+c.client+'\\n'+c.state).join('\\n\\n');document.querySelector('#error').textContent=''}catch(error){document.querySelector('#error').textContent=error.message}}
fetch('/meta').then(r=>r.json()).then(m=>{slider.min=m.start;slider.max=m.end;slider.value=m.start;document.querySelector('#meta').textContent='Build '+m.build+' · frames '+m.start+'–'+m.end+' · '+(m.divergenceScanned===false?'compare clients at the selected frame':m.firstDivergentFrame===null?'clients agree':'clients first differ at frame '+m.firstDivergentFrame);if(m.firstDivergentFrame!==null){const button=document.querySelector('#diverge');button.hidden=false;button.onclick=()=>{slider.value=m.firstDivergentFrame;show()}}show()});slider.oninput=show;
</script></body></html>`;
