// Generates TypeScript declarations for Warcraft's natives from common.j and
// blizzard.j files that describe the patch the map targets.
// Usage: bun scripts/natives.ts COMMON_J BLIZZARD_J OUT_D_TS
const [commonPath, blizzardPath, outPath] = process.argv.slice(2);
if (commonPath === undefined || blizzardPath === undefined || outPath === undefined) {
  throw new Error("usage: bun scripts/natives.ts COMMON_J BLIZZARD_J OUT_D_TS");
}

const PRIMITIVES: Record<string, string> = {
  integer: "number",
  real: "number",
  boolean: "boolean",
  string: "string",
  code: "(this: void) => void",
  nothing: "void",
};
// Natives that may legitimately return null in Lua are many; declare handle
// returns as possibly undefined only where callers must check (left to wrappers).
const RESERVED = new Set(["function", "class", "new", "delete", "in", "default", "var", "let", "const", "this", "type", "interface", "enum"]);

function tsType(jass: string): string {
  return PRIMITIVES[jass] ?? jass;
}

function parameters(list: string): string {
  if (list.trim() === "nothing") return "";
  return list
    .split(",")
    .map((parameter) => {
      const [type, name] = parameter.trim().split(/\s+/);
      const safe = RESERVED.has(name!) ? `${name}_` : name;
      return `${safe}: ${tsType(type!)}`;
    })
    .join(", ");
}

const out: string[] = [
  "// Generated by wisp:scripts/natives.ts from common.j and blizzard.j for the target Warcraft patch. Do not edit.",
  "/** @noSelfInFile */",
  "",
  "declare interface handle { readonly __handle: unique symbol }",
];
const declaredTypes = new Set(["handle"]);
const declaredValues = new Set<string>();

for (const path of [commonPath, blizzardPath]) {
  const source = await Bun.file(path).text();
  let inGlobals = false;
  for (const raw of source.split(/\r?\n/)) {
    const line = raw.replace(/\/\/.*$/, "").trim();
    if (line === "globals") { inGlobals = true; continue; }
    if (line === "endglobals") { inGlobals = false; continue; }
    let m: RegExpExecArray | null;
    if ((m = /^type\s+(\w+)\s+extends\s+(\w+)/.exec(line))) {
      if (!declaredTypes.has(m[1]!)) {
        out.push(`declare interface ${m[1]} extends ${m[2]} { readonly __${m[1]}: unique symbol }`);
        declaredTypes.add(m[1]!);
      }
      continue;
    }
    if ((m = /^(?:constant\s+)?native\s+(\w+)\s+takes\s+(.+?)\s+returns\s+(\w+)/.exec(line))
      || (m = /^function\s+(\w+)\s+takes\s+(.+?)\s+returns\s+(\w+)/.exec(line))) {
      if (declaredValues.has(m[1]!)) continue;
      declaredValues.add(m[1]!);
      out.push(`declare function ${m[1]}(${parameters(m[2]!)}): ${tsType(m[3]!)};`);
      continue;
    }
    if (inGlobals && (m = /^(constant\s+)?(\w+)\s+(array\s+)?(\w+)/.exec(line))) {
      const [, constant, type, array, name] = m;
      if (declaredValues.has(name!)) continue;
      declaredValues.add(name!);
      out.push(`declare ${constant ? "const" : "let"} ${name}: ${tsType(type!)}${array ? "[]" : ""};`);
    }
  }
}
await Bun.write(outPath, `${out.join("\n")}\n`);
console.log(`${declaredTypes.size} handle types, ${declaredValues.size} functions and globals`);

export {};
