// Native names added in Warcraft 3.0 and 3.0.1; signatures come from the checked patch build installed locally.
export const WARCRAFT3_NATIVES = [
  "ConvertFogStyle",
  "ConvertEquipmentType",
  "ConvertItemTag",
  "ConvertLoadoutSlot",
  "SetPlayerRaceSkin",
  "BlzTriggerIsRunning",
  "BlzTriggerInterrupt",
  "SetDestructableColor",
  "AllowHeroGlowOnUnit",
  "DisallowHeroGlowOnUnit",
  "HeroGlowIsAllowedOnUnit",
  "BlzGetUnitAnimationDuration",
  "BlzGetUnitAnimationDurationByIndex",
  "ChooseRandomItemExWithFilter",
  "SetTerrainFogExV",
  "BlzSetTerrainFogStyle",
  "BlzSetTerrainFogZStart",
  "BlzSetTerrainFogZEnd",
  "BlzSetTerrainFogDensity",
  "BlzSetTerrainFogHeightStart",
  "BlzSetTerrainFogHeightEnd",
  "BlzSetTerrainFogLinearStart",
  "BlzSetTerrainFogLinearEnd",
  "BlzSetTerrainFogMaxLinearDensity",
  "BlzSetTerrainFogDrawOverSky",
  "BlzSetTerrainFogColor",
  "BlzGetModelCinematicGameShotCount",
  "BlzGetModelCinematicGameCurrentShot",
  "BlzGetModelCinematicGameRemainingTime",
  "BlzPlayModelCinematicGameAtPosition",
  "BlzSetCinematicEnabledDE",
  "BlzSetMinShadowCastingPointLightCount",
  "BlzGetMinShadowCastingPointLightCount",
  "SetCameraFieldControlledByInput",
  "GetCameraFieldControlledByInput",
  "BlzCameraSetCameraType",
  "BlzCameraGetCameraType",
  "BlzCameraSetupSetCameraType",
  "BlzCameraSetupGetCameraType",
  "EnableCameraBlocker",
  "AddCameraBlocker",
  "BlzPauseThematicMusicOnFocusLost",
  "SetHDWaterParams",
  "SetHDWaterParamsEx",
  "BlzSetHDWaterColor",
  "BlzSetHDWaterColorOverride",
  "BlzSetHDWaterVertexDisplacement",
  "BlzSetHDWaterMinOpacity",
  "BlzSetHDWaterMaxOpacity",
  "BlzSetHDWaterReflectivity",
  "BlzSetHDWaterEmissivity",
  "BlzSetHDWaterEdgeSoftness",
  "BlzSetHDWaterWaveStrength",
  "BlzSetHDWaterEnvMapStrength",
  "BlzIsTerrainPathableEx",
  "BlzSetSingleDoodadAnimation",
  "SetDoodadColor",
  "SetDoodadColorRect",
  "BlzSetSingleDoodadColor",
  "BlzGetDoodadX",
  "BlzGetDoodadY",
  "BlzGetDoodadZ",
  "BlzGetDoodadScaleX",
  "BlzGetDoodadScaleY",
  "BlzGetDoodadScaleZ",
  "BlzGetDoodadIsUsingModelAxes",
  "BlzGetDoodadYaw",
  "BlzGetDoodadPitch",
  "BlzGetDoodadRoll",
  "BlzGetDoodadVariation",
  "BlzGetDoodadId",
  "BlzGetNumDoodads",
  "BlzResetUnitAttack",
  "BlzSetSpecialEffectAnimationBlendTime",
  "BlzQueueSpecialEffectAnimation",
  "BlzSetSpecialEffectAnimation",
  "BlzUnitEnableAuras",
  "BlzGetUnitAbilityCooldownPercent",
  "BlzSetUnitAbilityCooldownRemaining",
  "BlzSetUnitAbilityCooldownPercent",
  "BlzAdjustUnitAbilityCooldownRemaining",
  "BlzAdjustUnitAbilityCooldownPercent",
  "BlzTextAreaFrameSetAutoScroll",
  "BlzIsMetaKeyPressed",
  "BlzIsKeyPressed",
  "BlzIsMouseButtonPressed",
  "BlzGetMouseScreenPosX",
  "BlzGetMouseScreenPosY",
  "BlzPixelToFrameX",
  "BlzPixelToFrameY",
  "BlzFrameToPixelX",
  "BlzFrameToPixelY",
  "BlzCreateDestructablePitchRoll",
  "BlzCreateDestructableZPitchRoll",
  "BlzCreateDeadDestructablePitchRoll",
  "BlzCreateDeadDestructableZPitchRoll",
  "BlzCreateDestructableWithSkinPitchRoll",
  "BlzCreateDestructableZWithSkinPitchRoll",
  "BlzCreateDeadDestructableWithSkinPitchRoll",
  "BlzCreateDeadDestructableZWithSkinPitchRoll",
  "BlzCreateDestructableWithColor",
  "BlzCreateDestructableZWithColor",
  "BlzCreateDeadDestructableWithColor",
  "BlzCreateDeadDestructableZWithColor",
  "BlzCreateDestructableWithSkinColor",
  "BlzCreateDestructableZWithSkinColor",
  "BlzCreateDeadDestructableWithSkinColor",
  "BlzCreateDeadDestructableZWithSkinColor",
  "BlzCreateDestructablePitchRollWithColor",
  "BlzCreateDestructableZPitchRollWithColor",
  "BlzCreateDeadDestructablePitchRollWithColor",
  "BlzCreateDeadDestructableZPitchRollWithColor",
  "BlzCreateDestructableWithSkinPitchRollColor",
  "BlzCreateDestructableZWithSkinPitchRollColor",
  "BlzCreateDeadDestructableWithSkinPitchRollColor",
  "BlzCreateDeadDestructableZWithSkinPitchRollColor",
  "SetDestructableVertexColor",
  "BlzGetEquippedItem",
  "BlzGetUnequippedItem",
  "BlzSetItemColor",
  "BlzIsItemEquipped",
  "BlzIsItemInBag",
  "BlzGetItemEquipmentType",
  "BlzGetItemTag",
  "BlzUnitEquipItem",
  "BlzUnitUnequipItem",
  "BlzUnitUnequipItemFromSlot",
  "BlzUnitHasItemBagged",
  "BlzUnitExtendedInventorySize",
  "BlzUnitItemInBagSlot",
  "BlzUnitItemInEquipmentSlot",
  "BlzUnitHasItemEquipped",
  "BlzUnitHasLoadoutSlotEmpty",
  "BlzUnitHasAnyItemEquipped",
  "BlzUnitHasItemEquipmentOfType",
  "BlzUnitCanEquipItemOfEquipmentType",
  "BlzUnitHeal",
  "BlzResetUnitTalents",
  "ChooseRandomItemExWithFilterAndIncludes",
  "BlzPreloadModelCinematicGame",
  "BlzGetHUDScale",
  "BlzGetCameraAllowsHotkeyTargetLock",
  "BlzSetCameraAllowsHotkeyTargetLock",
  "BlzSetThematicMusicAbsoluteVolume",
  "BlzRemoveEffect"
] as const;

export const WARCRAFT3_ENUM_VALUES: Readonly<Record<string, number>> = {
  "FOG_STYLE_LINEAR": 0,
  "FOG_STYLE_EXP": 1,
  "FOG_STYLE_EXP2": 2,
  "FOG_STYLE_HEIGHT": 3,
  "FOG_STYLE_NEW_EXP": 4,
  "FOG_STYLE_NEW_EXP_2": 5,
  "EQUIPMENT_TYPE_NONE": 0,
  "EQUIPMENT_TYPE_HEAD": 1,
  "EQUIPMENT_TYPE_CHEST": 2,
  "EQUIPMENT_TYPE_GLOVES": 3,
  "EQUIPMENT_TYPE_BOOTS": 4,
  "EQUIPMENT_TYPE_RING": 5,
  "EQUIPMENT_TYPE_PRIMARY": 6,
  "EQUIPMENT_TYPE_OFFHAND": 7,
  "EQUIPMENT_TYPE_TRINKET": 8,
  "EQUIPMENT_TYPE_ANY": 9,
  "ITEMTAG_TYPE_UNDEFINED": 0,
  "ITEMTAG_TYPE_DROPPABLE": 1,
  "ITEMTAG_TYPE_QUESTREWARD": 2,
  "ITEMTAG_TYPE_BOSSDROP": 3,
  "ITEMTAG_TYPE_SECRET": 4,
  "ITEMTAG_TYPE_PUZZLE": 5,
  "ITEMTAG_TYPE_WORLD": 6,
  "ITEMTAG_TYPE_SHOP": 7,
  "ITEMTAG_TYPE_ANY": 8,
  "EQUIPMENT_LOADOUT_SLOT_HEAD": 0,
  "EQUIPMENT_LOADOUT_SLOT_CHEST": 1,
  "EQUIPMENT_LOADOUT_SLOT_GLOVES": 2,
  "EQUIPMENT_LOADOUT_SLOT_BOOTS": 3,
  "EQUIPMENT_LOADOUT_SLOT_RING": 4,
  "EQUIPMENT_LOADOUT_SLOT_RINGALT": 5,
  "EQUIPMENT_LOADOUT_SLOT_PRIMARY": 6,
  "EQUIPMENT_LOADOUT_SLOT_OFFHAND": 7,
  "EQUIPMENT_LOADOUT_SLOT_TRINKET": 8
};
